codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: 65%
        threshold: 5%
        if_ci_failed: error

    patch:
      default:
        target: 60%
        threshold: 10%
        # Make patch coverage informational - don't block PRs
        # Useful for refactoring commits that remove code
        informational: true

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  # Test files
  - "**/*_test.go"
  - "tests/**"

  # Test infrastructure (not production code)
  - "internal/testutil/**"
  - "internal/integration/**"

  # Test mocks
  - "internal/shell/mock_executor.go"

  # Embedded files (templates, not code)
  - "internal/embed/files/**"

  # Entry point (minimal testable code)
  - "main.go"
