version: 2

run:
  timeout: 5m
  skip-dirs:
    - docker

linters:
  # Les defaults (errcheck, govet, ineffassign, staticcheck, unused) sont déjà activés
  enable:
    - misspell       # Fautes d'orthographe
    - bodyclose      # Fermeture des HTTP response bodies
    - gocritic       # Checks supplémentaires de qualité

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
