package compose

import (
	"fmt"
	"strconv"
	"strings"
)

// Options for docker-compose generation
type Options struct {
	WorkerCount      int
	RedisPort        int                // External port (default 6379)
	ContainerPrefix  string             // Prefix for container names (default "hive")
	QueenDockerfile  string             // Dockerfile for queen (default "docker/Dockerfile.node")
	WorkerDockerfile string             // Dockerfile for workers (default "docker/Dockerfile.node")
	QueenPorts       []string           // Port mappings for queen (e.g., "3000:13000")
	WorkerPorts      []string           // Port mappings for workers (auto-incremented)
	PortsPerDrone    map[int][]string   // Per-drone port mappings (e.g., 1: ["4200:4200"])
	ExtraVolumes     []string           // Additional volume mounts for all agents
	PlaywrightMode   string             // "headless" or "connect"
	BrowserEndpoint  string             // WebSocket endpoint for Playwright connect mode
	CACertPath       string             // Path to CA certificate for corporate proxy
	ExtraHosts       []string           // Extra /etc/hosts entries (e.g., "host.docker.internal:host-gateway")
	NetworkEnv       map[string]string  // Network-related environment variables
}

// Generate creates a docker-compose.yml content with the specified options
func Generate(workerCount int) string {
	return GenerateWithOptions(Options{
		WorkerCount:     workerCount,
		RedisPort:       6379,
		ContainerPrefix: "hive",
	})
}

// GenerateWithOptions creates a docker-compose.yml with full options
func GenerateWithOptions(opts Options) string {
	var sb strings.Builder

	if opts.RedisPort == 0 {
		opts.RedisPort = 6379
	}
	if opts.ContainerPrefix == "" {
		opts.ContainerPrefix = "hive"
	}
	if opts.QueenDockerfile == "" {
		opts.QueenDockerfile = "docker/Dockerfile.node"
	}
	if opts.WorkerDockerfile == "" {
		opts.WorkerDockerfile = "docker/Dockerfile.node"
	}

	prefix := opts.ContainerPrefix

	// Header
	sb.WriteString(`# Generated by hive init - DO NOT EDIT MANUALLY
# Re-run 'hive init' to regenerate with different worker count

services:
`)

	// Redis service with authentication
	sb.WriteString(fmt.Sprintf(`  redis:
    image: redis:7-alpine
    container_name: %s-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "%d:6379"
    env_file:
      - .env
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - %s-network

`, prefix, opts.RedisPort, prefix))

	// Queen service
	// Note: paths are relative to .hive/ where docker-compose.yml lives
	sb.WriteString(fmt.Sprintf(`  queen:
    build:
      context: .
      dockerfile: %s
    container_name: %s-queen
    hostname: queen
    env_file:
      - .env
    environment:
      - AGENT_ROLE=queen
      - AGENT_NAME=queen
      - CLAUDE_MODEL=${QUEEN_MODEL:-opus}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
`, opts.QueenDockerfile, prefix))

	// Add Playwright environment variables if configured
	if opts.PlaywrightMode != "" {
		sb.WriteString(fmt.Sprintf("      - PLAYWRIGHT_MODE=%s\n", opts.PlaywrightMode))
	}
	if opts.BrowserEndpoint != "" {
		sb.WriteString(fmt.Sprintf("      - PLAYWRIGHT_BROWSER_ENDPOINT=%s\n", opts.BrowserEndpoint))
	}

	// Add network environment variables (for duck services, etc.)
	for key, value := range opts.NetworkEnv {
		sb.WriteString(fmt.Sprintf("      - %s=%s\n", key, value))
	}

	// Add extra_hosts if configured (for host.docker.internal on Linux)
	if len(opts.ExtraHosts) > 0 {
		sb.WriteString("    extra_hosts:\n")
		for _, host := range opts.ExtraHosts {
			sb.WriteString(fmt.Sprintf("      - \"%s\"\n", host))
		}
	}

	// Add queen ports if configured
	if len(opts.QueenPorts) > 0 {
		sb.WriteString("    ports:\n")
		for _, port := range opts.QueenPorts {
			sb.WriteString(fmt.Sprintf("      - \"%s\"\n", port))
		}
	}

	sb.WriteString(`    volumes:
      - ./workspaces/queen:/workspace
      - node-modules-queen:/workspace/node_modules
      - ../.git:/workspace-git
      - ../.claude:/workspace/.claude
      - .:/hive-config:ro
      - ./shared:/hive-shared
      - ${HOME}/.claude/mcps:/home/agent/.claude/mcps:ro
      - ${HOME}/.claude/plugins:/home/agent/.claude/plugins:ro
      - ${HOME}/.config/gh:/home/agent/.config/gh:ro
      - ${HOME}/.config/glab-cli:/home/agent/.config/glab-cli:ro
      - ${HOME}/.gitconfig:/home/agent/.gitconfig:ro
      - ${HOME}/.ssh:/home/agent/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - pnpm-store-queen:/home/agent/.local/share/pnpm
      - node-modules-cache:/home/agent/node_modules_cache
      - tools-cache:/home/agent/.tools-cache
      - ./workspaces/queen/.claude-projects:/home/agent/.claude/projects
`)

	// Add extra volumes if configured
	for _, vol := range opts.ExtraVolumes {
		sb.WriteString(fmt.Sprintf("      - %s\n", vol))
	}

	sb.WriteString(fmt.Sprintf(`    depends_on:
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true
    networks:
      - %s-network

`, prefix))

	// Worker services
	for i := 1; i <= opts.WorkerCount; i++ {
		sb.WriteString(generateWorkerService(i, prefix, opts))
	}

	// Networks section
	sb.WriteString(fmt.Sprintf(`networks:
  %s-network:
    driver: bridge

volumes:
  redis-data:
  pnpm-store-queen:
  node-modules-queen:
`, prefix))

	// Add pnpm-store and node-modules volume for each drone
	for i := 1; i <= opts.WorkerCount; i++ {
		sb.WriteString(fmt.Sprintf("  pnpm-store-drone-%d:\n", i))
		sb.WriteString(fmt.Sprintf("  node-modules-drone-%d:\n", i))
	}

	sb.WriteString(`  node-modules-cache:
  tools-cache:
`)

	return sb.String()
}

// generateWorkerService generates a single worker service block
// Note: paths are relative to .hive/ where docker-compose.yml lives
func generateWorkerService(index int, prefix string, opts Options) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf(`  drone-%d:
    build:
      context: .
      dockerfile: %s
    container_name: %s-drone-%d
    hostname: drone-%d
    env_file:
      - .env
    environment:
      - AGENT_ROLE=worker
      - AGENT_NAME=drone-%d
      - CLAUDE_MODEL=${WORKER_MODEL:-sonnet}
      - WORKER_MODE=${WORKER_MODE:-interactive}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
`, index, opts.WorkerDockerfile, prefix, index, index, index))

	// Add Playwright environment variables if configured
	if opts.PlaywrightMode != "" {
		sb.WriteString(fmt.Sprintf("      - PLAYWRIGHT_MODE=%s\n", opts.PlaywrightMode))
	}
	if opts.BrowserEndpoint != "" {
		sb.WriteString(fmt.Sprintf("      - PLAYWRIGHT_BROWSER_ENDPOINT=%s\n", opts.BrowserEndpoint))
	}

	// Add network environment variables (for duck services, etc.)
	for key, value := range opts.NetworkEnv {
		sb.WriteString(fmt.Sprintf("      - %s=%s\n", key, value))
	}

	// Get port mappings for this drone (for HIVE_EXPOSED_PORTS)
	dronePorts := opts.PortsPerDrone[index]
	var effectivePorts []string
	if len(dronePorts) > 0 {
		effectivePorts = dronePorts
	} else if len(opts.WorkerPorts) > 0 {
		// Calculate auto-incremented ports
		for _, port := range opts.WorkerPorts {
			effectivePorts = append(effectivePorts, incrementPortForWorker(port, index))
		}
	}

	// Add HIVE_EXPOSED_PORTS for autonomous testing (port discovery)
	if len(effectivePorts) > 0 {
		sb.WriteString(fmt.Sprintf("      - HIVE_EXPOSED_PORTS=%s\n", formatPortMappings(effectivePorts)))
	}
	// Add HIVE_HOST_BASE for constructing test URLs
	sb.WriteString("      - HIVE_HOST_BASE=host.docker.internal\n")

	// Add extra_hosts if configured (for host.docker.internal on Linux)
	if len(opts.ExtraHosts) > 0 {
		sb.WriteString("    extra_hosts:\n")
		for _, host := range opts.ExtraHosts {
			sb.WriteString(fmt.Sprintf("      - \"%s\"\n", host))
		}
	}
	// Add port mappings (using effectivePorts already calculated above)
	if len(effectivePorts) > 0 {
		sb.WriteString("    ports:\n")
		for _, port := range effectivePorts {
			sb.WriteString(fmt.Sprintf("      - \"%s\"\n", port))
		}
	}

	sb.WriteString(fmt.Sprintf(`    volumes:
      - ./workspaces/drone-%d:/workspace
      - node-modules-drone-%d:/workspace/node_modules
      - ../.git:/workspace-git
      - ../.claude:/workspace/.claude
      - .:/hive-config:ro
      - ./shared:/hive-shared
      - ${HOME}/.claude/mcps:/home/agent/.claude/mcps:ro
      - ${HOME}/.claude/plugins:/home/agent/.claude/plugins:ro
      - ${HOME}/.config/gh:/home/agent/.config/gh:ro
      - ${HOME}/.config/glab-cli:/home/agent/.config/glab-cli:ro
      - ${HOME}/.gitconfig:/home/agent/.gitconfig:ro
      - ${HOME}/.ssh:/home/agent/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - pnpm-store-drone-%d:/home/agent/.local/share/pnpm
      - node-modules-cache:/home/agent/node_modules_cache
      - tools-cache:/home/agent/.tools-cache
      - ./workspaces/drone-%d/.claude-projects:/home/agent/.claude/projects
`, index, index, index, index))

	// Add extra volumes if configured
	for _, vol := range opts.ExtraVolumes {
		sb.WriteString(fmt.Sprintf("      - %s\n", vol))
	}

	sb.WriteString(fmt.Sprintf(`    depends_on:
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true
    networks:
      - %s-network

`, prefix))

	return sb.String()
}

// incrementPortForWorker takes a port mapping like "3000:13000" and increments
// the host port based on the worker index (drone-1 gets +0, drone-2 gets +1, etc.)
func incrementPortForWorker(portMapping string, workerIndex int) string {
	parts := strings.Split(portMapping, ":")
	if len(parts) != 2 {
		return portMapping // Invalid format, return as-is
	}

	containerPort := parts[0]
	hostPort, err := strconv.Atoi(parts[1])
	if err != nil {
		return portMapping // Can't parse, return as-is
	}

	// Increment host port: drone-1 uses base port, drone-2 uses base+1, etc.
	newHostPort := hostPort + workerIndex - 1
	return fmt.Sprintf("%s:%d", containerPort, newHostPort)
}

// formatPortMappings converts a list of port mappings to a comma-separated string
// for the HIVE_EXPOSED_PORTS environment variable.
// Input: ["3000:13000", "8081:18081"]
// Output: "3000:13000,8081:18081"
func formatPortMappings(ports []string) string {
	return strings.Join(ports, ",")
}
