package compose

import (
	"fmt"
	"strings"
)

// Options for docker-compose generation
type Options struct {
	WorkerCount int
	RedisPort   int // External port (default 6379)
}

// Generate creates a docker-compose.yml content with the specified options
func Generate(workerCount int) string {
	return GenerateWithOptions(Options{
		WorkerCount: workerCount,
		RedisPort:   6379,
	})
}

// GenerateWithOptions creates a docker-compose.yml with full options
func GenerateWithOptions(opts Options) string {
	var sb strings.Builder

	if opts.RedisPort == 0 {
		opts.RedisPort = 6379
	}

	// Header
	sb.WriteString(`# Generated by hive init - DO NOT EDIT MANUALLY
# Re-run 'hive init' to regenerate with different worker count

services:
`)

	// Redis service
	sb.WriteString(fmt.Sprintf(`  redis:
    image: redis:7-alpine
    container_name: hive-redis
    ports:
      - "%d:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - hive-network

`, opts.RedisPort))

	// Queen service
	// Note: paths are relative to .hive/ where docker-compose.yml lives
	sb.WriteString(`  queen:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
    container_name: hive-queen
    hostname: queen
    env_file:
      - .env
    environment:
      - AGENT_ROLE=queen
      - AGENT_NAME=queen
      - CLAUDE_MODEL=${QUEEN_MODEL:-opus}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./workspaces/queen:/workspace
      - ../.git:/workspace-git
      - ../.claude:/workspace/.claude
      - .:/hive-config:ro
      - ${HOME}/.claude/mcps:/home/agent/.claude/mcps:ro
      - ${HOME}/.claude/plugins:/home/agent/.claude/plugins:ro
      - ${HOME}/.config/gh:/home/agent/.config/gh:ro
      - ${HOME}/.gitconfig:/home/agent/.gitconfig:ro
      - ${HOME}/.ssh:/home/agent/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - pnpm-store-queen:/home/agent/.local/share/pnpm
      - node-modules-cache:/home/agent/node_modules_cache
      - tools-cache:/home/agent/.tools-cache
    depends_on:
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true
    networks:
      - hive-network

`)

	// Worker services
	for i := 1; i <= opts.WorkerCount; i++ {
		sb.WriteString(generateWorkerService(i))
	}

	// Volumes section - each agent gets its own pnpm-store to avoid race conditions
	sb.WriteString(`networks:
  hive-network:
    driver: bridge

volumes:
  redis-data:
  pnpm-store-queen:
`)

	// Add pnpm-store volume for each drone
	for i := 1; i <= opts.WorkerCount; i++ {
		sb.WriteString(fmt.Sprintf("  pnpm-store-drone-%d:\n", i))
	}

	sb.WriteString(`  node-modules-cache:
  tools-cache:
`)

	return sb.String()
}

// generateWorkerService generates a single worker service block
// Note: paths are relative to .hive/ where docker-compose.yml lives
func generateWorkerService(index int) string {
	return fmt.Sprintf(`  drone-%d:
    build:
      context: .
      dockerfile: docker/Dockerfile.node
    container_name: hive-drone-%d
    hostname: drone-%d
    env_file:
      - .env
    environment:
      - AGENT_ROLE=worker
      - AGENT_NAME=drone-%d
      - CLAUDE_MODEL=${WORKER_MODEL:-sonnet}
      - WORKER_MODE=${WORKER_MODE:-interactive}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./workspaces/drone-%d:/workspace
      - ../.git:/workspace-git
      - ../.claude:/workspace/.claude
      - .:/hive-config:ro
      - ${HOME}/.claude/mcps:/home/agent/.claude/mcps:ro
      - ${HOME}/.claude/plugins:/home/agent/.claude/plugins:ro
      - ${HOME}/.config/gh:/home/agent/.config/gh:ro
      - ${HOME}/.gitconfig:/home/agent/.gitconfig:ro
      - ${HOME}/.ssh:/home/agent/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - pnpm-store-drone-%d:/home/agent/.local/share/pnpm
      - node-modules-cache:/home/agent/node_modules_cache
      - tools-cache:/home/agent/.tools-cache
    depends_on:
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true
    networks:
      - hive-network

`, index, index, index, index, index, index)
}
