package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/mbourmaud/hive/internal/shell"
	"github.com/mbourmaud/hive/internal/ui"
	"github.com/spf13/cobra"
)

// Default port mappings for exposed services
var defaultPorts = map[string]string{
	"3000":  "13000", // Backend API
	"4000":  "14000", // Alt backend
	"5000":  "15000", // Alt backend
	"8080":  "18080", // Web server
	"8081":  "18081", // Metro bundler
	"19000": "19000", // Expo
	"19001": "19001", // Expo
	"19002": "19002", // Expo
}

var exposeCmd = &cobra.Command{
	Use:   "expose <agent>",
	Short: "Expose development ports for an agent",
	Long: `Expose development ports for an agent container to allow
browser/simulator access to services running inside.

This creates a docker-compose.expose.yml overlay and restarts
the specified agent with port mappings.

Examples:
  hive expose drone-1     # Expose ports for drone-1
  hive expose queen       # Expose ports for queen
  hive expose drone-1 --ports 3000,8080  # Expose specific ports only`,
	Args: cobra.ExactArgs(1),
	RunE: runExpose,
}

var exposePorts string
var exposeReset bool

func init() {
	rootCmd.AddCommand(exposeCmd)
	exposeCmd.Flags().StringVarP(&exposePorts, "ports", "p", "", "Comma-separated list of container ports to expose (default: common dev ports)")
	exposeCmd.Flags().BoolVar(&exposeReset, "reset", false, "Remove port exposures and restart with default config")
}

func runExpose(cmd *cobra.Command, args []string) error {
	agent := args[0]

	// Validate agent name
	validAgents := []string{"queen", "drone-1", "drone-2", "drone-3", "drone-4", "drone-5"}
	isValid := false
	for _, v := range validAgents {
		if agent == v {
			isValid = true
			break
		}
	}
	if !isValid {
		return fmt.Errorf("invalid agent: %s (valid: queen, drone-1, drone-2, ...)", agent)
	}

	// Check if .hive directory exists
	if _, err := os.Stat(".hive"); os.IsNotExist(err) {
		return fmt.Errorf("no .hive directory found. Run 'hive init' first")
	}

	overlayPath := filepath.Join(".hive", "docker-compose.expose.yml")

	// Handle reset
	if exposeReset {
		fmt.Print(ui.Header("🔌", fmt.Sprintf("Removing port exposure for %s", agent)))

		if err := removeAgentFromOverlay(overlayPath, agent); err != nil {
			return err
		}

		// Restart the agent
		runner := shell.NewRunner(DebugMode)
		restartCmd := exec.Command("docker", "compose",
			"-f", ".hive/docker-compose.yml",
			"up", "-d", agent)
		if err := runner.RunWithTitle(restartCmd, "Restarting agent"); err != nil {
			return fmt.Errorf("failed to restart agent: %w", err)
		}

		fmt.Printf("\n%s\n\n", ui.Success(fmt.Sprintf("Ports removed for %s", agent)))
		return nil
	}

	// Header
	fmt.Print(ui.Header("🔌", fmt.Sprintf("Exposing ports for %s", agent)))

	// Determine which ports to expose
	ports := defaultPorts
	if exposePorts != "" {
		ports = make(map[string]string)
		for _, p := range strings.Split(exposePorts, ",") {
			p = strings.TrimSpace(p)
			if p == "" {
				continue
			}
			// Map to host port with prefix 1 to avoid conflicts
			if len(p) == 4 {
				ports[p] = "1" + p
			} else {
				ports[p] = p
			}
		}
	}

	// Generate overlay content
	overlay := generateExposeOverlay(agent, ports)

	// Write overlay file
	if err := os.WriteFile(overlayPath, []byte(overlay), 0644); err != nil {
		return fmt.Errorf("failed to write overlay file: %w", err)
	}
	fmt.Printf("  %s Created %s\n", ui.StyleGreen.Render("✓"), overlayPath)

	// Create shell runner
	runner := shell.NewRunner(DebugMode)

	// Restart the specific agent with overlay
	restartCmd := exec.Command("docker", "compose",
		"-f", ".hive/docker-compose.yml",
		"-f", overlayPath,
		"up", "-d", agent)
	if err := runner.RunWithTitle(restartCmd, "Restarting with ports"); err != nil {
		return fmt.Errorf("failed to restart agent: %w", err)
	}

	// Show exposed ports
	fmt.Printf("\n%s\n\n", ui.StyleBold.Render("Exposed ports:"))
	for container, host := range ports {
		fmt.Printf("  %s → localhost:%s\n",
			ui.StyleDim.Render(fmt.Sprintf("container:%s", container)),
			ui.StyleGreen.Render(host))
	}

	fmt.Printf("\n%s\n", ui.StyleDim.Render("Access services at:"))
	fmt.Printf("  Backend API: %s\n", ui.StyleCyan.Render("http://localhost:13000"))
	fmt.Printf("  Metro:       %s\n", ui.StyleCyan.Render("http://localhost:18081"))
	fmt.Printf("  Expo:        %s\n", ui.StyleCyan.Render("exp://localhost:19000"))

	fmt.Printf("\n%s\n\n", ui.Success(fmt.Sprintf("Ports exposed for %s!", agent)))
	return nil
}

func generateExposeOverlay(agent string, ports map[string]string) string {
	var portLines []string
	for container, host := range ports {
		portLines = append(portLines, fmt.Sprintf(`      - "%s:%s"`, host, container))
	}

	return fmt.Sprintf(`# Generated by hive expose - port mappings overlay
services:
  %s:
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${HOST_IP:-host.docker.internal}
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    ports:
%s
`, agent, strings.Join(portLines, "\n"))
}

func removeAgentFromOverlay(overlayPath, agent string) error {
	// Simply remove the overlay file if it exists
	// A more sophisticated approach would parse and remove just this agent
	if _, err := os.Stat(overlayPath); err == nil {
		if err := os.Remove(overlayPath); err != nil {
			return fmt.Errorf("failed to remove overlay: %w", err)
		}
	}
	return nil
}
